name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
assignees:
- ILmpf
type: bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug! Please fill out the form below.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: What did you observe?
      placeholder: Describe the problem clearly.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: What should have happened?
    validations:
      required: false

